apiVersion: audit.k8s.io/v1
kind: policy
omitStages:
  - "ResponseComplet"
rules:
  - level: Metadata
    verbs: ["get", "list", "watch"]
    namespaces: ["kube-system"]
      - group: ""
        resources: ["configmaps", "services"]
    omitStages:
      - "RequestReceived"
  - level: Request
    resources:
      - group: ""
        resources: ["secrets"]
  - level: RequestResponse
    resources:
      - group: ""
        resources: ["pod"]
  - level: none