apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-frontend
  name: app-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-frontend
  name: client-access
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    context: frontend
