apiVersion: v1
kind: Pod
metadata:
  name: insecured-workload
spec:
  volumes:
  - name: nicehost
    hostPath:
      path: /
  hostPID: true
  containers:
  - name: unsafe-container
    image: busybox
    command: ["sleep", "3600"]
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nicehost
      mountPath: /host
    securityContext:
      privileged: true
      runAsUser: 0
