---
apiVersion: v1
kind: Namespace
metadata:
  name: netpolicy-problem
  labels:
    problem: netpolicy
---
apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: netpolicy-problem
  labels:
    role: server
spec:
  containers:
  - image: nginx
    name: server
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: netpolicy-problem
  labels:
    role: client
spec:
  containers:
  - image: alpine
    name: client
    command: ["/bin/sh","-c","sleep infinity"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-server-access
  namespace: netpolicy-problem
spec:
  podSelector:
    matchLabels:
      role: server
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          problem: netproblem
      podSelector:
        matchLabels:
          role: clint
    ports:
    - protocol: TCP
      port: 8080
