apiVersion: v1
kind: Pod
metadata:
  name: pod-debug-image
  labels:
    app: pod-debug-image
spec:
  containers:
  - name: image-pull
    image: busybox:1.36.1
    imagePullPolicy: Never
    command: ["/bin/sh", "-c", "echo image is successfully pulled"]
