#Crossplane MR Problem 1

apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: rx-m-crossplane-bad-bucket-
spec:
  forProvider:
    region: us-west-6
    objectLockEnabled: true
    tags:
      Name: bad-bucket
      Vendor: RX-M
